name: Build and Release on Icon Library Update

on:
  push:
    branches:
      - main
    paths:
      - 'package.json'  # Trigger when dependency is updated
  pull_request:
    branches:
      - main
    paths:
      - 'package.json'

permissions:
  id-token: write  # Required for OIDC
  contents: write
  pull-requests: write
  packages: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        env:
          NODE_ENV: production

      - name: Sync version with icon library
        run: pnpm run sync-version

      - name: Commit changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add package.json
          git commit -m "chore: sync version with icon library"
          git push

      - name: Build
        run: pnpm run build

      - name: Publish to npm
        if: github.event_name == 'push'
        run: npm publish --provenance --access public --no-git-checks
        env:
          # it is currently imperative to set NODE_AUTH_TOKEN to an empty string for OIDC auth to work
          # https://github.com/actions/setup-node/blob/633bb92bc0aabcae06e8ea93b85aecddd374c402/src/authutil.ts#L57
          NODE_AUTH_TOKEN: ""